# site settings
title: Coccin'ailes
subtitle: Du Pays d'Allevard
email: ml@fatbsd.com #bureau@coccinailes.fr
description: Club de Parapente et de Vol Libre du Pays d'Allevard
baseurl:
url:
author: Jérôme LOYET
street_address: C/O LABY Romain
street_address_2: 7 lot. le Closy Jolie Vue
city: Allevard
state:
zip_code: 38580
country: France
phone:
title_logo_left: assets/images/logo_without_text_transparent_dark.png
title_logo_right: assets/images/logo_without_text_transparent_dark.png

collections:
- decollages
- atterrissages

# social settings
500px_url:
youtube_url: https://www.youtube.com/channel/UCWCtfjqP8renxPCQgUVazkA
facebook_url: https://www.facebook.com/groups/coccinailes.fr/
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown
exclude: [CNAME, Gemfile*]
plugins:
  - jekyll-sitemap

sass:
  style: compressed

